### PR TITLE
Disabled Paging Toolbars fix

### LINKED ISSUE #1775: Paging Toolbars Freeze if User Constantly Refresh Pages
Bellow this description there is a list of paging toolbars that freeze, if user presses Refresh key and then presses and holds Enter key (so Kapua has to constantly refresh the item list). User has to create 100+ items, so there are at elast two pages of them. 

Main paging toolbar is the paging toolbar of item list (e.g. groups list, jobs list, etc.).

Problematic paging toolbars:
 - Main paging toolbar in Connections when pressed -> "Search"/"Reset" button in Filter
 - Main paging toolbar in Device -> "Search"/"Reset" buttons in Filter
 - Paging toolbar for Events in Devices  -> disabled stat eby default
 - Main paging toolbar  in Batch jobs -> "Search"/"Reset" button in Filter
 - Data -> By Devices/By Assets -> Refresh button by Prefix Filter
 - Main paging toolbar  in Tags -> "Search"/"Reset" button in Filter
 - Assigned Devices Paging toolbar in Tags when pressed -> Refresh button in main T 
 - Main paging toolbar  in Users -> "Search"/"Reset" button in Filter
 - Main paging toolbar  in Roles -> "Search"/"Reset" button in Filter
 - Main paging toolbar  in Access Groups  -> "Search"/"Reset" button in Filter
 - Main paging toolbar  in Child Accounts  -> "Search"/"Reset" button in Filter
 - Main paging toolbar  in Endpoints  -> "Search"/"Reset" button in Filter

**Testflow:**
1. Login as kapua-sys or any other user with proper permissions
2. Go to Devices/Jobs/Tags...and create 100+ items 
3. Follow the instructions above (e.g. pressing refresh button in Filter panel multile times) to see the result. 

**Expected behaviour:**
Paging toolbar should never get grayed out as consequence of pressing a button multiple times.

**Sample Screenshot:**
screen shot 2018-06-07 at 16 44 45

**Version of Kapua**
 - 1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console 
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit)
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.1  (64-bit))
- Opera (Version 53.0.2907.57)

### PR DESCRIPTION
**Pull request by ct-ajovanovic**
Brief description of the PR.
Paging Toolbars are no longer disabled after grid load/refresh

**Related Issue**
This PR fixes/closes #1775 

**Description of the solution adopted**
Added new constructor for `EntityGridLoadListener` class, with refresh and reset buttons as parameters. Depending on the grid loading stage these buttons are enabled/disabled.  This new constructor is then used in the `EntityGrid` class if these buttons from `EntityFilterPanel` are passed as parameters. 
Also Paging Toolbars from Device Events and Assigned Devices tabs, which were disabled by default or after grid refresh are now enabled as well.
**Screenshots**
_None_

**Any side note on the changes made**
_None_

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
I have verified that this PR successfully resolves issue _1775_. @Coduz can you please check this and merge if OK?

File: console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/client/ui/grid/EntityGrid.java [hunk 1]
```diff
@@ -161,7 +162,11 @@ protected void configureEntityGrid() {
 
         //
         // Grid Data Load Listener
-        EntityGridLoadListener<M> entityGridLoadListener = new EntityGridLoadListener<M>(this, entityStore);
+        if (EntityFilterPanel.getSearchButton() != null && EntityFilterPanel.getResetButton() != null) {
```
Comment (lorthirk) [inline console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/client/ui/grid/EntityGrid.java]: It looks like `EntityGridLoadListener` handles null values of `searchButton` and `resetButton` gracefully so, unless I'm missing something, I'm not sure that this if / else block is needed. You could just call the four parameters constructor and let the `EntityGridLoadListener` handle the cases where `EntityFilterPanel.getResetButton()` and `EntityFilterPanel.getResetButton()` are null. What do you think?

**Comment by ct-ajovanovic** [comment]
@lorthirk Yes, you were right! I removed the unnecessary  null check.  It was already handled in `EntityGridLoadListener` . Can you please take a look at this again?
Thanks
_Aleksandra_
