### PR TITLE
Users view now uses Entity View Template

### LINKED ISSUE #218: Refactor Users view to support EntityView template
Users view needs to be refactored to use EntityView templates

### LINKED ISSUE #253: New user cannot log on
Creating a new user in state "enabled" creates a user which cannot log on to the system.

When the user tries to log on the following message is shown instead: Subject does not have permission [user:read:1:*]

```
11:42:03,291 [qtp1145319246-115] WARN  KapuaExceptionHandler:90  - RPC service non-application error
org.apache.shiro.authz.UnauthorizedException: Subject does not have permission [user:read:1:*]
	at org.apache.shiro.authz.ModularRealmAuthorizer.checkPermission(ModularRealmAuthorizer.java:334)
	at org.apache.shiro.mgt.AuthorizingSecurityManager.checkPermission(AuthorizingSecurityManager.java:141)
	at org.apache.shiro.subject.support.DelegatingSubject.checkPermission(DelegatingSubject.java:210)
	at org.eclipse.kapua.service.authorization.shiro.AuthorizationServiceImpl.checkPermission(AuthorizationServiceImpl.java:60)
	at org.eclipse.kapua.service.user.internal.UserServiceImpl.find(UserServiceImpl.java:170)
	at org.eclipse.kapua.app.console.server.GwtAuthorizationServiceImpl.establishSession(GwtAuthorizationServiceImpl.java:178)
	at org.eclipse.kapua.app.console.server.GwtAuthorizationServiceImpl.login(GwtAuthorizationServiceImpl.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

### LINKED ISSUE #254: Modifying user permissions does not work
Opening a user and modifying permissions does not work:

Steps to reproduce:
* Open user details
* Check previously unchecked user permission
* Press "Submit"

→ Nothing happens

Expected result: record gets updated or error message shown instead

### LINKED ISSUE #255: Validation errors may be hidden from the user
Validation errors, blocking the dialog to "submit", may stay out of sight for a user:

* Open user edit dialog
* Switch to "Permissions"
* Press "Submit"

→ Nothing happens
→ The first tab (when switching back) shows two field validation errors (password)

Expected result: The user should be made aware of the fact that the dialog cannot be submitted due to validation errors.

### LINKED ISSUE #256: Unable to edit user details without entering a new password
When you want to edit user details it is currently required to also assign a new password. It is possible to enter the same password though.

However, traditionally, editing user information (like permissions and telephone number) is different tasks and should not also require to update the password. Which should not be known by the person editing the current user anyway.

### PR DESCRIPTION
**Pull request by lorthirk**
Hi all,

This PR refactors Users view so that it now uses the View Template.

Resolves #218 and, indirectly, resolves #253, resolves #254, resolves #255, resolves #256.

### CODE REVIEW

File: console/src/main/java/org/eclipse/kapua/app/console/client/user/dialog/UserAddDialog.java [hunk 1]
```diff
@@ -0,0 +1,206 @@
...
+        gwtUserCreator.setDisplayName(displayName.getValue());
+        gwtUserCreator.setEmail(email.getValue());
+        gwtUserCreator.setPhoneNumber(phoneNumber.getValue());
+        
+        gwtUserService.create(xsrfToken, gwtUserCreator, new AsyncCallback<GwtUser>() {
+
+            @Override
+            public void onSuccess(GwtUser arg0) {
+                m_exitStatus = true;
+                m_exitMessage = "OK"; // TODO Localize
```
Comment (Coduz) [inline console/src/main/java/org/eclipse/kapua/app/console/client/user/dialog/UserAddDialog.java]: I've localized it! Is here! 😂

File: console/src/main/java/org/eclipse/kapua/app/console/client/user/dialog/UserAddDialog.java [hunk 2]
```diff
@@ -0,0 +1,206 @@
...
+            @Override
+            public void onFailure(Throwable cause) {
+                unmask();
+                
+                m_submitButton.enable();
+                m_cancelButton.enable();
+                m_status.hide();
+                
+                m_exitStatus = false;
+                m_exitMessage = "KO"; // TODO Localize with cause
```
Comment (Coduz) [inline console/src/main/java/org/eclipse/kapua/app/console/client/user/dialog/UserAddDialog.java]: I've localized because it is commented!

File: console/src/main/java/org/eclipse/kapua/app/console/client/user/dialog/UserAddDialog.java [hunk 3]
```diff
@@ -0,0 +1,206 @@
...
+            }
+        });
+        
+        System.out.println("create user");
+
+    }
+
+    @Override
+    public String getHeaderMessage() {
+        return "Title";
```
Comment (Coduz) [inline console/src/main/java/org/eclipse/kapua/app/console/client/user/dialog/UserAddDialog.java]: Localize

File: console/src/main/java/org/eclipse/kapua/app/console/client/user/dialog/UserAddDialog.java [hunk 4]
```diff
@@ -0,0 +1,206 @@
...
+    }
+
+    @Override
+    public String getInfoMessage() {
+        return "Info";
```
Comment (Coduz) [inline console/src/main/java/org/eclipse/kapua/app/console/client/user/dialog/UserAddDialog.java]: Localize

File: console/src/main/java/org/eclipse/kapua/app/console/client/user/tabs/role/AccessRoleAddDialog.java [hunk 5]
```diff
@@ -0,0 +1,160 @@
...
+                m_status.hide();
+                
+                m_exitStatus = false;
+                m_exitMessage = MSGS.dialogAddError(MSGS.dialogAddRoleError(cause.getLocalizedMessage()));
+                
+                hide();
+            }
+        });
+        
+        System.out.println("create role");
```
Comment (Coduz) [inline console/src/main/java/org/eclipse/kapua/app/console/client/user/tabs/role/AccessRoleAddDialog.java]: Can you please remove it?

File: console/src/main/java/org/eclipse/kapua/app/console/client/user/tabs/role/UserTabItemAccessRole.java [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+import org.eclipse.kapua.app.console.shared.model.user.GwtUser;
+
+import com.google.gwt.user.client.Element;
+
+public class UserTabItemAccessRole extends KapuaTabItem<GwtUser> {
+
+    private UserTabAccessRoleGrid accessRoleGrid;
+
+    public UserTabItemAccessRole(GwtSession currentSession) {
+        super("Roles", new KapuaIcon(IconSet.STREET_VIEW));
```
Comment (Coduz) [inline console/src/main/java/org/eclipse/kapua/app/console/client/user/tabs/role/UserTabItemAccessRole.java]: Localize

File: console/src/main/java/org/eclipse/kapua/app/console/client/user/dialog/UserAddDialog.java (hunk 1 above)
Comment (lorthirk) [inline console/src/main/java/org/eclipse/kapua/app/console/client/user/dialog/UserAddDialog.java]: Funny 😄
