### PR TITLE
Manage sortFields unmarshalling in REST Datastore queries

### LINKED ISSUE #2123: Retrieval of sorted messages via REST
**Describe the bug**
If we have too much data in Kapua (> 10000 entries), its REST API doesn’t allow us to get the last sent payload. But it does allow to get the first. In web UI the logic is reversed – we can only get the most recent 10000 entries. A solution where sort order would be requested doesn't work i.e. still returns oldest messages in ascending order.

**To Reproduce**
1. Connect a device to Kapua
2. Fill some data e.g. 10 messages by Kura's ExamplePublisher
3. Authenticate and fetch 5 most recent messages through REST:
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer <fill it>' -d '{
  "limit": 5,
  "scopeId": {
    "id": "<fill it>"
  },
  "predicate": {},
  "fetchAttributes": [
    "string"
  ],
  "fetchStyle": "FIELDS",
  "askTotalCount": true,
  "sortFields": [
    {
      "sortDirection": "DESC",
      "field": "sentOn"
    }
  ],
  "offset": 0
}' 'https://<host>/v1/<fill it>/data/messages/_query'
```

**Expected behavior**
Messages are returned in descending order of `sentOn` i.e. most recent first.

**Screenshots**
In web UI results up to now are available. Result from REST instead of screenshots:
```
{
  "type": "storableListResult",
  "limitExceeded": false,
  "size": 5,
  "items": [
    {
      "type": "jsonDatastoreMessage",
      "capturedOn": "2018-10-04T08:34:30.651Z",
      "channel": {
        "semanticParts": [
          "heater",
          "data"
        ]
      },
      "clientId": "B8:27:EB:33:A7:1A",
      "deviceId": "PZtzsLMAPXQ",
      "payload": {
        ...
      },
      "receivedOn": "2018-10-04T08:39:09.009Z",
      "scopeId": "...",
      "sentOn": "2018-10-04T08:34:30.651Z",
      "datastoreId": "6d6d2707-1534-4631-9ca0-c21128f62215",
      "timestamp": "2018-10-04T08:34:30.651Z"
    },
    {
      "type": "jsonDatastoreMessage",
      "capturedOn": "2018-10-04T08:34:31.649Z",
      "channel": {
        "semanticParts": [
          "heater",
          "data"
        ]
      },
      "clientId": "B8:27:EB:33:A7:1A",
      "deviceId": "PZtzsLMAPXQ",
      "payload": {
        ...
      },
      "receivedOn": "2018-10-04T08:39:10.055Z",
      "scopeId": "...",
      "sentOn": "2018-10-04T08:34:31.649Z",
      "datastoreId": "733e0c40-e8c8-44c2-aab0-49507d9e4e8e",
      "timestamp": "2018-10-04T08:34:31.649Z"
    },
    <additional 3 more recent messages>
  ]
}
```

**Version of Kapua**
current

**Main component affected**
[ ] REST API

### PR DESCRIPTION
**Pull request by lorthirk**
Currently we manage only a few fields when unmarshalling a Query object in a REST Datastore query, as per #803. This PR implements unmarshalling for sortFields specifically in `/data/messages/_query`.
Brief description of the PR.[e.g. Added `null` check on `object` to avoid `NullPointerException`]

**Related Issue**
This PR is related to #803, although it doesn't fix it completely. Also fixes #2123 

**Description of the solution adopted**
Previously, the `sortFields` property was marked as `@XmlTransient`, so the first step was to remove such annotation. Additionally, two different models have been implemented in order to correctly manage unmarshalling in XML and JSON.

**Screenshots**
N/A

**Any side note on the changes made**
N/A

### CODE REVIEW

File: rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DataMessagesJson.java [hunk 1]
```diff
@@ -172,24 +177,24 @@ public StorableEntityId storeMessageJson(
...
-            @ApiParam(value = "The DatastoreMessageQuery to use to filter results", required = true) MessageQuery query) throws Exception {
+            @ApiParam(value = "The DatastoreMessageQuery to use to filter results", required = true) JsonMessageQuery query) throws Exception {
         query.setScopeId(scopeId);
 
-        MessageListResult result = DATA_MESSAGES.query(scopeId, query);
+        MessageListResult result = DATA_MESSAGES.query(scopeId, convertQuery(query));
 
-        List<JsonDatastoreMessage> asd = new ArrayList<>();
-        result.getItems().forEach(m -> asd.add(new JsonDatastoreMessage(m)));
+        List<JsonDatastoreMessage> jsonDatastoreMessages = new ArrayList<>();
```
Comment (Coduz) [inline rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DataMessagesJson.java]: Ops 😛
