### PR TITLE
Unable To Save New Settings fix

### LINKED ISSUE #1961: Unable To Save New Settings As Kapua-sys
If user is logged in as kapua-sys, Kapua does not let user to save new settings in Settings tab (look at the screenshot) - pressing Submit causes screen to flash and nothing happens. 

**Testflow:**
1) Login as kapua-sys
2) Go to Settings, change a setting (e.g. Phone Number) 
3) Press Submit
**Observe how Kapua does not save changes, but instead of this screen only flashes.**

**Screenshot No. 1 (immediatelly after pressing Submit button):**
screen shot 2018-08-31 at 11 08 25

**Screenshot No. 2 (After Submit is released - Kapua should close the window and save settings, but it does not):**
screen shot 2018-08-31 at 11 08 39

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

### PR DESCRIPTION
**Pull request by ct-ajovanovic**
Brief description of the PR.
Unable To Save New Settings fix

**Related Issue**
This PR fixes/closes #1961 

**Description of the solution adopted**
Added a null check for _oldAccount.getScopeId()_ when creating a parentAccount in update() function of the AccountServiceImpl class. Set ScopeId when adding a new account to _currentSession.getSelectedAccountId()_ .  Also set the correct value to be displayed for parent account name on the AccountEditDialog.

**Screenshots**
_None_

**Any side note on the changes made**
_None_

Signed-off-by: ct-ajovanovic <aleksandra.jovanovic@comtrade.com>

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
I have verified that this PR successfully resovles issue **1961.** @muros-ct can you please check the solution and merge when all tests complete?

File: console/module/account/src/main/java/org/eclipse/kapua/app/console/module/account/client/toolbar/AccountEditDialog.java [hunk 1]
```diff
@@ -47,6 +47,23 @@ protected void onRender(Element parent, int pos) {
...
+                @Override
+                public void onSuccess(GwtAccount result) {
+                    if (parentAccountNameLabel != null) {
+                        parentAccountNameLabel.setValue(result.getName());
+                    }
+                }
+
+                @Override
+                public void onFailure(Throwable caught) {
+                    caught.printStackTrace();
```
Comment (Coduz) [inline console/module/account/src/main/java/org/eclipse/kapua/app/console/module/account/client/toolbar/AccountEditDialog.java]: Please use `FailureHandler` class.

File: service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountServiceImpl.java [hunk 2]
```diff
@@ -151,6 +151,7 @@ public Account update(Account account) throws KapuaException {
         ArgumentValidator.notEmptyOrNull(account.getName(), "account.name");
         ArgumentValidator.notNull(account.getOrganization(), "account.organization");
         ArgumentValidator.match(account.getOrganization().getEmail(), CommonsValidationRegex.EMAIL_REGEXP, "account.organization.email");
+        Account parentAccount = null;
```
Comment (Coduz) [inline service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountServiceImpl.java]: Please move this close to where is first used (L174)

**Comment by ct-ajovanovic** [comment]
@Coduz @LeoNerdoG I made the requested changes. Can you please take a look at this again?

**Comment by LeoNerdoG** [comment]
Hey @ct-ajovanovic I have rechecked this and have verified, that this solves issue _**1961**_.
@Coduz can you please check the fixes and merge when possible?
