### PR TITLE
fix lifecycle processing throws a NPE for a not defined account

### LINKED ISSUE #162: Lifecycle processing throws a NPE for a not defined account
If a not defined account is contained in the lifecycle message channel the lifecycle processing throws a NPE.
Switch it to a KapuaEntityNotFoundException.

### PR DESCRIPTION
**Pull request by riccardomodanese**
Signed-off-by: riccardomodanese <riccardo.modanese@eurotech.com>

fix #162

### CODE REVIEW

File: translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/TranslatorLifeAppsKuraKapua.java [hunk 1]
```diff
@@ -50,6 +50,10 @@ public KapuaAppsMessage translate(KuraAppsMessage kuraAppsMessage)
         AccountService accountService = locator.getService(AccountService.class);
         Account account = accountService.findByName(kuraAppsMessage.getChannel().getScope());
 
+        if (account == null) {
+            throw new KapuaEntityNotFoundException(Account.class.toString(), kuraAppsMessage.getChannel().getScope());
```
Comment (Coduz) [inline translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/TranslatorLifeAppsKuraKapua.java]: Hi @riccardomodanese ,

please change the throw parameter from `Account.class.toString()` to `Account.getType()`
Same for all other changes.

Regards,

_Alberto_
