### PR TITLE
Fix for String Channel values not displayed correctly

### LINKED ISSUE #2597: String Channel Values Not Parsed Correctly
If user has a device with some String assests (with sample valuse such as "string" or "123"), these strings are not properly parsed when displaying in Kapua - so instead "string" and "132" we get &amp;quot;string&amp;quot; and &amp;quot;123&amp;quot;

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Connect a live Kura device to Kapua (e.g. device0) with some sample drivers (e.g. driver0) and assets (e.g. asset0), that have String channels with values "string"
3. In Kapua, go to Devices -> device0 -> Assets and observe the values of the assets

**Expected behavior:**
Double quotes should be parsed as double quotes and not as `&quot'`.

**Screenshot:**
Screenshot 2019-05-14 at 09 28 09

**Version of Kapua**
1.1.0-SNAPSHOT

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 74.0.3729.131 (Official Build) (64-bit))
- Safari (Version 12.1)
- Mozilla Firefox (66.0.3 (64-bit))
- Opera (Version:60.0.3255.70)

### PR DESCRIPTION
**Pull request by ct-ajovanovic**
Signed-off-by: Aleksandra Jovanovic <aleksandra.jovanovic@comtrade.com>

Brief description of the PR.
Fix for String Channel values not displayed correctly.

**Related Issue**
This PR fixes/closes #2597 

**Description of the solution adopted**
Solved problems when displaying special characters in the Assets -> Channel fields. 
The string value is unescaped using the `KapuaSafeHtmlUtils.htmlUnescape(String)` method. 
Also the `htmlUnescape()` method was updated:
- the if check for `&amp;` string and its replacement with `&` was moved to first place (more efficient as all other cases look for the `&` and not `&amp;` at the beginning of the string)
- added new _if case to_ check for `amp;` which is sometimes unnecessarily added and should be removed (like `amp;amp;amp;amp;amp;` after the first ` &amp;` in `&amp;amp;amp;amp;amp;amp;quot;string&amp;` )

**Screenshots**
_None_

**Any side note on the changes made**
_None_

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
I have verified that this PR successfully resolves issue #2597. The only problem is when sending special symbols from Kapua to Kura (the other way around is OK) - in this case the string does not get parsed correctly, but that is issue for Kura project. 
Can one of the commiters check the solution and merge if everything is OK?

File: console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/client/util/KapuaSafeHtmlUtils.java [hunk 1]
```diff
@@ -30,6 +30,12 @@ public static String htmlUnescape(String safeHtml) {
             return null;
         }
 
+        if (safeHtml.indexOf("&amp;") != -1) {
+            safeHtml = safeHtml.replace("&amp;", "&");
+        }
+        if (safeHtml.indexOf("amp;") != -1) {
```
Comment (Coduz) [inline console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/client/util/KapuaSafeHtmlUtils.java]: Wouldn't this change every occurrence of the string "amp" in every string?

Comment (ct-ajovanovic) [reply console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/client/util/KapuaSafeHtmlUtils.java]: @Coduz To answer your question, this wouldn't change every occurrence of the string `amp` but  only `amp;`.
There are cases where we have one or multiple unnecessary instances of `amp;` string added, like here:
`&amp;amp;amp;amp;amp;amp;quot;string&amp;`
the sting `&amp;` gets displayed correctly as `&` but we are still have multiple `amp;` instances that prevent the complete "unescape" for all of the string characters, and we are left with something like this:
`&amp;amp;amp;amp;amp;quot;string&;`
The string is partially "unescaped" but not completely.
With this solution the unnecessary `amp;` is  removed, and the correct value displayed after only one `htmlUnescape` call.
I guess that there is also the case where the user intentionally enters `amp` as a part of the string. But what probability is it for it to be entered in combination with`;` ?
What do you think?

Comment (muros-ct) [reply console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/client/util/KapuaSafeHtmlUtils.java]: @Coduz Is it ok to merge this?
