### PR TITLE
Command field validation and error message fix

### LINKED ISSUE #1715: Number of Characters in Command Window in Devices Not Limited
When entering commands into Command field, problem emerges, if command is too long and contains special symbols (some of theme work like line "breakers" - look at the screenshot).

Testflow: 
1. Login as kapua-sys or any other user with proper priviliges (Broker:ALL, Device:ALL, Device_management:ALL, Device_lifecycle:ALL)
2. Connect a live Kura device to Kapua (e.g. device0)
3. Go to Devices, select device0 and go to its Command tab
4. Enter a very long useles command (e.g. 123456789ertyuifghjvb<.,<<.#$%&'(UYFVBN_:;>_:;@‹›€ı”ÓÔˇ¿È.-.1,2-3.,-3.,1-23.,1-.,-.,23>:_>;_:>;_..1-23....)
**Observe how Kapua puts this command into multiple lines (try with a very long command - as seen on screenshot).**

screen shot 2018-05-18 at 12 59 14

Browsers used: 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit)
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.1  (64-bit))
- Opera (Version 53.0.2907.57)

### PR DESCRIPTION
**Pull request by ct-ajovanovic**
Brief description of the PR.
Command field validation and error message fix

**Related Issue**
This PR fixes #1715 

**Description of the solution adopted**
Added maxLength() property to the command field, set maxLengthText to custom message. Changed text for the error message thrown when invalid command is entered with another custom message. Added these messages to ConsoleDeviceMessages class.

**Screenshots**
None

**Any side note on the changes made**
None

Signed-off-by: ct-ajovanovic <aleksandra.jovanovic@comtrade.com>

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
I have verified that this PR successfully resolves issue #1715. @Coduz can you please check the code and see if the solution provided is OK?

File: console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/command/DeviceTabCommand.java [hunk 1]
```diff
@@ -218,10 +219,10 @@ public void handleEvent(FormEvent be) {
                     if (UNDEFINED_ERROR.equals(errorMessage)) {
                         errorMessage = DEVICE_MSGS.deviceConnectionError();
                     } else if (errorMessage.contains(INTERNAL_ERROR)) {
-                        errorMessage = errorMessage.substring(errorMessage.indexOf(INTERNAL_ERROR) + INTERNAL_ERROR.length() + 1,
-                                errorMessage.indexOf(": error="));
+                        errorMessage = DEVICE_MSGS.deviceCommandExecutionErrorMessage();
                     }
-                    MessageBox.alert(MSGS.error(), MSGS.commandExecutionFailure() + ":<br/>" + errorMessage, null);
+                    StyleInjector.inject(".x-window-dlg .ext-mb-icon {width: 50px; height: 50px;}");
```
Comment (muros-ct) [inline console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/command/DeviceTabCommand.java]: Is this the only way?

**Comment by muros-ct** [comment]
@lorthirk Is it ok to use StyleInjector like this?

File: console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/command/DeviceTabCommand.java (hunk 1 above)
Comment (Coduz) [reply console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/command/DeviceTabCommand.java]: I think that we can change this to be a `InfoDialog`. Would make sense?
